#PBS -N fastqc_sheep
#PBS -M johndou@umich.edu
#PBS -m abe
#PBS -V

#PBS -l walltime=24:00:00
#PBS -l procs=1,pmem=2gb

#PBS -q fluxod
#PBS -A bakulski_fluxod
#PBS -l qos=flux

cat $PBS_NODEFILE

module load fastqc/0.11.5

for path in /nfs/turbo/bakulski1/Datasets/Padmanabhan/ruddle.brcf.med.umich.edu/Run_2742/padmanabha/Sample_124*; do

	SAMPLEID="$(basename "${path}")"
	
	mkdir /nfs/turbo/bakulski1/People/johndou/vsheep/Run_2742/fastqc/$SAMPLEID/
	
	fastqc \
	/nfs/turbo/bakulski1/Datasets/Padmanabhan/ruddle.brcf.med.umich.edu/Run_2742/padmanabha/$SAMPLEID/*.fastq.gz \
	--outdir=/nfs/turbo/bakulski1/People/johndou/vsheep/Run_2742/fastqc/$SAMPLEID/

done


module load python-anaconda3

cd /nfs/turbo/bakulski1/People/johndou/vsheep/Run_2742/fastqc/
python /nfs/turbo/bakulski1/People/johndou/import_multiqc.py

multiqc \
/nfs/turbo/bakulski1/People/johndou/vsheep/Run_2742/fastqc/Sample_124*